### ISSUE TITLE
Добавьте поддержку актуальной версии Prestashop (1.7.7.x)

### ISSUE THREAD

**Issue by evgenij-sobolev** [platonua/PrestaShop_1.6.0.9_Ukraine#1]
Добрый день!
Версия престашоп 1.6.0.9 уже устарела.
Сейчас большинство магазинов переходят на актуальную версию 1.7.7.х

**Comment by platonua** [comment]
Добрый день!
Версия 1.7 добавлена по ссылке https://github.com/platonua/PrestaShop_1.7_Ukraine
